[tool.ruff]
line-length = 79
target-version = "py313"
exclude = ["alembic"]

[tool.ruff.lint]
preview = true
select = ["E", "F", "I", "N", "W"]
extend-select = ["E501", "E302", "E303"]
ignore = ["N805"]

[tool.ruff.lint.isort]
force-sort-within-sections = false
force-single-line = false
combine-as-imports = true
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
known-first-party = ["db_handler", "filters", "keyboards", "utils"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
line-ending = "lf"
preview = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
